version: '3.4'

services:
  client:
    image: qwx1337/blogchain-client:latest
    links:
      - server
    environment:
      CDN_HOST: ${CDN_HOST} 
      API_HOST: ${API_HOST}
    ports:
      - 3000:3000
  server:
    image: qwx1337/blogchain-server:latest
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_DIALECT: ${DATABASE_DRIVER}
      CLICKHOUSE_ADDRESS: ${CLICKHOUSE_ADDRESS}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE}
      CDN_HOST: ${CDN_HOST} 
      CDN_USER: ${CDN_USER}
      CDN_PASSWORD: ${CDN_PASSWORD}
      BIND_SOCKET: ${BIND_SOCKET}
      LISTENER: ${LISTENER}
      BIND_ADDRESS: ${BIND_ADDRESS}
      CONTAINER_SECRET: ${CONTAINER_SECRET}
    ports:
      - 3001:3001
  fileserver:
    image: qwx1337/go-fileserver:latest
    volumes:
      - $HOME/tmp:/app/tmp
      - $PWD:/mnt
    links:
      - server
      - client
    environment:
      BIND_ADDRESS: '0.0.0.0:1338'
      SECURE_TYPE: 1
      USERS: ${FILESERVER_USERS}
      ENABLE_SECURE: 'true'
      ENABLE_TSL: 'true'
      TSL_CERT_FILE: '/mnt/server.crt'
      TSL_KEY_FILE: '/mnt/server.key'
    ports:
      - 1338:1338
volumes:
  
